networks:
  docker-vnet:
    external: true

services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    restart: unless-stopped
    networks:
      - docker-vnet
    ports:
      - 3552:3552/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - ${HOME}/services:/app/data/projects
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
